#!/bin/bash
cd /home/pi/surprise

until test $(ps ax | grep -c rsyslogd) -gt 1; do sleep 2; done
logger run_surprise found rsyslogd
until $(netstat -nat | grep -q '0.0.0.0:31280.*LISTEN'); do sleep 2; done
logger run_surprise found dweeb server
until test -c /dev/input/event0; do sleep 2; done
logger run_surprise found clicker device
sleep 3
while true; do 
	./runSurpriseDweeb.py
	sleep 2
done
